server:
  port: 5002
volume-path: ${user.home}/Desktop/DummyFiles/
eureka:     #tells about the Eureka server details and its refresh time
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: storage-service   #current service name to be used by the eureka server